# Generated by Django 2.1 on 2017-12-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171217_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categroy',
            new_name='category',
        ),
    ]
